services:

  postgres:
    image: postgres:15
    container_name: customers-postgres
    environment:
      POSTGRES_DB: customersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customersdb"]
      interval: 5s
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:3-management
    container_name: customers-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  postgres_audit:
    image: postgres:16
    container_name: postgres_audit
    environment:
      POSTGRES_DB: auditdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_audit_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auditdb"]
      interval: 5s
      timeout: 5s
      retries: 20

  customer-service:
    build: ./customer-service
    container_name: customer-service
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customersdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"

  audit-service:
    build: ./audit-service
    container_name: audit-service
    depends_on:
      postgres_audit:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_audit:5432/auditdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8081:8081"

  frontend:
    build: ./customer-frontend
    container_name: customer-frontend
    depends_on:
      - customer-service
    ports:
      - "5173:5173"
    volumes:
      - ./customer-frontend:/app      # 1. Espelha sua pasta local para dentro do container
      - /app/node_modules             # 2. "Protege" a pasta node_modules do container (truque essencial!)
    environment:
      # Se você usar variáveis de ambiente no front, declare aqui:
      - VITE_API_URL=http://localhost:8080

volumes:
  postgres_data:
  postgres_audit_data:
