FROM eclipse-temurin:21-jdk-jammy

WORKDIR /app

COPY mvnw pom.xml ./
COPY .mvn .mvn

RUN ./mvnw -B dependency:go-offline

COPY src src

RUN ./mvnw -B package -DskipTests

EXPOSE 8081

ENTRYPOINT ["java","-jar","target/audit-service-0.0.1-SNAPSHOT.jar"]