FROM eclipse-temurin:21-jdk-jammy


WORKDIR /app

# Copia wrapper e pom
COPY mvnw pom.xml ./
COPY .mvn .mvn

# Baixa dependências
RUN ./mvnw -B dependency:go-offline

# Copia o código
COPY src src

# Build
RUN ./mvnw -B package -DskipTests

EXPOSE 8080

ENTRYPOINT ["java","-jar","target/customer-service-0.0.1-SNAPSHOT.jar"]